spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dnilay/config-server-repo-22.git
  application:
    name: config-ws
  boot:
    admin:
      client:
        url:
        - http://localhost:5000
server:
  port: 2222