server:
  port: 8080
spring:
  application:
    name: order-ws
  datasource:
    url: jdbc:mysql://18.234.62.0:3306/emp
    username: root
    password: test1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'