server:
  port: 9999
spring:
  application:
    name: gateway-ws

  cloud:
    config:
      uri:
      - http://localhost:2222
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
         
eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'